---

- name: Remove podman-docker if installed
  yum:
    name: podman-docker
    state: absent

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: latest

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open port 80 in firewalld
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

